Made improvements to ./develop such as a better prompt, proper exit code handling and support for the new host + container output directories.

diff --git a/develop b/develop
--- a/develop
+++ b/develop
@@ -18,19 +18,18 @@ elif [ ${ENTRY_POINT} == "dotnet" ]; then
         exit 1;
     fi
 
-    echo "Could not execute command properly. Do you wish to remove the bin/Debug directory and rerun the initial command? [Y\n]";
+    echo -e 'Could not execute command successfully.\nDo you wish to remove the Debug directory and rerun the initial command? [Y/n]';
     read;
 
-    if echo ${REPLY} | grep -q -e "[Yy]"; then
-        docker exec -it "${DOCKER_CONTAINER_PREFIX}-api-1" rm -rf bin/Debug;
-        
-        echo "bin/Debug directory has been deleted.";
-
-        docker exec -it "${DOCKER_CONTAINER_PREFIX}-api-1" dotnet ${USER_ARGS}
-        exit;
+    if ! echo ${REPLY} | grep -q -e "[Yy]"; then
+        exit 1;
     fi
 
-    exit 1;
+    docker exec -it "${DOCKER_CONTAINER_PREFIX}-api-1" rm -rf bin/container/Debug;
+    echo "bin/container/Debug directory has been deleted.";
+
+    docker exec -it "${DOCKER_CONTAINER_PREFIX}-api-1" dotnet ${USER_ARGS}
+
 elif [ ${ENTRY_POINT} == "psql" ]; then
     docker exec -it "${DOCKER_CONTAINER_PREFIX}-database-1" psql -U lms -d lms ${USER_ARGS};
 elif [ ${ENTRY_POINT} == "npm" ]; then
